### ISSUE TITLE
Logo design proposal

### ISSUE THREAD

**Issue by Tobaloidee** [adventam10/AMColorPicker#4]
Good day @adventam10  I am a graphics designer and open source contributor. I want to contribute to your good project by proposing a logo design for the project which i will be doing for free as a gift. If you will give me permission i will start as soon as possible. Thanks and best regards!

-Tobaloidee

**Comment by adventam10** [comment]
Thank you for nice proposal.I really appreciate it.I'm looking forward to it.Thank you and best regards!

-adventam10

**Comment by Tobaloidee** [comment]
I came up with this design @adventam10  I hope you like it! still open for your modifications and suggestions.

![amcolorpicker-01-01](https://user-images.githubusercontent.com/36028424/41730864-70c3afee-75af-11e8-94a3-ae712880c367.png)

**Comment by adventam10** [comment]
It's great! I like it so much. The concept is easy to understand.

**Comment by Tobaloidee** [comment]
Is it the version on top? Im glad that you liked it  :) should i make a PR now and upload the files and update the readme?

**Comment by adventam10** [comment]
Yes, it's the version on top. Yes, please.

**Comment by Tobaloidee** [comment]
Hi, I already made a PR #5 for the logo files upload and readme update. 

Thanks and my best regards to the project!

-Tobaloidee

**Comment by adventam10** [comment]
Thank you so much!
